import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english
    case vietnamese

    var id: String { rawValue }

    var label: String {
        switch self {
        case .english:
            "English"
        case .vietnamese:
            "Tiếng Việt"
        }
    }
}

enum AppStrings {
    static func text(_ key: String, language: AppLanguage) -> String {
        switch language {
        case .english:
            english[key] ?? key
        case .vietnamese:
            vietnamese[key] ?? english[key] ?? key
        }
    }

    private static let english = [
        "all": "All",
        "text": "Text",
        "link": "Link",
        "code": "Code",
        "stack": "Stack",
        "clipboard": "Clipboard",
        "quickPanel": "Quick Panel",
        "quickPanelSubtitle": "Quick access to daily tools",
        "searchAnything": "Search anything...",
        "recentActivity": "Recent activity",
        "clipboardSubtitle": "History, boards and copy stack",
        "capture": "Capture",
        "captureSubtitle": "Screenshots and OCR",
        "screenshot": "Screenshot",
        "aiOcr": "AI / OCR",
        "translate": "Translate",
        "search": "Search",
        "settingsShort": "Settings",
        "media": "Media",
        "mediaSubtitle": "Now playing controls",
        "calendar": "Calendar",
        "calendarSubtitle": "Events and reminders",
        "aiAgents": "AI Agents",
        "agentsSubtitle": "Coding-agent sessions",
        "flaggedFeature": "This tool is staged behind a feature flag.",
        "searchClipboard": "Search clipboard...",
        "emptyClipboard": "Copy something to start building local history.",
        "copy": "Copy",
        "copyNext": "Copy next",
        "clearStack": "Clear stack",
        "removeFromStack": "Remove from stack",
        "moveEarlier": "Move earlier",
        "moveLater": "Move later",
        "addToStack": "Add to stack",
        "addToBoard": "Add to board",
        "removeFromBoard": "Remove from board",
        "favorite": "Favorite",
        "unfavorite": "Remove favorite",
        "deleteItem": "Delete item",
        "moveLeft": "Move left",
        "moveRight": "Move right",
        "newBoard": "New board",
        "boardDefaultName": "Board",
        "rename": "Rename",
        "delete": "Delete",
        "renameBoard": "Rename board",
        "deleteBoard": "Delete board",
        "deleteBoardQuestion": "Delete board?",
        "deleteBoardMessage": "Clipboard items stay in All. Only this board is removed.",
        "boardName": "Board name",
        "save": "Save",
        "cancel": "Cancel",
        "settingsGeneral": "General",
        "settingsNotch": "Notch",
        "settingsClipboard": "Clipboard",
        "settingsSync": "Sync",
        "settingsPrivacy": "Privacy",
        "settingsShortcuts": "Shortcuts",
        "settingsAdvanced": "Advanced",
        "settingsAbout": "About",
        "launchAtLogin": "Launch at login",
        "showInMenuBar": "Show in menu bar",
        "startMinimized": "Start minimized",
        "appearance": "Appearance",
        "theme": "Theme",
        "system": "System",
        "light": "Light",
        "dark": "Dark",
        "language": "Language",
        "panelShortcut": "Panel shortcut",
        "translation": "Translation",
        "ignoredApps": "Ignored Apps",
        "analytics": "Analytics",
        "off": "Off",
        "status": "Status",
        "configuredLocally": "Configured locally",
        "pauseClipboard": "Pause clipboard monitoring",
        "clearClipboard": "Clear clipboard history",
        "clearClipboardQuestion": "Clear clipboard history?",
        "clearClipboardMessage": "This permanently removes local clipboard items from this Mac. Boards are kept.",
        "cloudSync": "Cloud sync",
        "privacyBody": "Clipboard contents stay on this Mac unless you explicitly enable sync.",
        "openSettings": "Open Settings"
    ]

    private static let vietnamese = [
        "all": "Tất cả",
        "text": "Văn bản",
        "link": "Liên kết",
        "code": "Mã",
        "stack": "Stack",
        "clipboard": "Clipboard",
        "quickPanel": "Bảng nhanh",
        "quickPanelSubtitle": "Truy cập nhanh công cụ hằng ngày",
        "searchAnything": "Tìm mọi thứ...",
        "recentActivity": "Hoạt động gần đây",
        "clipboardSubtitle": "Lịch sử, board và copy stack",
        "capture": "Chụp màn hình",
        "captureSubtitle": "Ảnh chụp và OCR",
        "screenshot": "Screenshot",
        "aiOcr": "AI / OCR",
        "translate": "Dịch",
        "search": "Tìm kiếm",
        "settingsShort": "Cài đặt",
        "media": "Media",
        "mediaSubtitle": "Điều khiển đang phát",
        "calendar": "Lịch",
        "calendarSubtitle": "Sự kiện và nhắc việc",
        "aiAgents": "AI Agents",
        "agentsSubtitle": "Phiên coding-agent",
        "flaggedFeature": "Công cụ này đang nằm sau feature flag.",
        "searchClipboard": "Tìm clipboard...",
        "emptyClipboard": "Hãy sao chép nội dung để bắt đầu lịch sử cục bộ.",
        "copy": "Sao chép",
        "copyNext": "Sao chép mục kế tiếp",
        "clearStack": "Xóa stack",
        "removeFromStack": "Xóa khỏi stack",
        "moveEarlier": "Chuyển lên trước",
        "moveLater": "Chuyển xuống sau",
        "addToStack": "Thêm vào stack",
        "addToBoard": "Thêm vào board",
        "removeFromBoard": "Xóa khỏi board",
        "favorite": "Yêu thích",
        "unfavorite": "Bỏ yêu thích",
        "deleteItem": "Xóa mục",
        "moveLeft": "Chuyển sang trái",
        "moveRight": "Chuyển sang phải",
        "newBoard": "Board mới",
        "boardDefaultName": "Board",
        "rename": "Đổi tên",
        "delete": "Xóa",
        "renameBoard": "Đổi tên board",
        "deleteBoard": "Xóa board",
        "deleteBoardQuestion": "Xóa board?",
        "deleteBoardMessage": "Các mục clipboard vẫn nằm trong Tất cả. Chỉ board này bị xóa.",
        "boardName": "Tên board",
        "save": "Lưu",
        "cancel": "Hủy",
        "settingsGeneral": "Chung",
        "settingsNotch": "Notch",
        "settingsClipboard": "Clipboard",
        "settingsSync": "Đồng bộ",
        "settingsPrivacy": "Riêng tư",
        "settingsShortcuts": "Phím tắt",
        "settingsAdvanced": "Nâng cao",
        "settingsAbout": "Giới thiệu",
        "launchAtLogin": "Mở khi đăng nhập",
        "showInMenuBar": "Hiện trên menu bar",
        "startMinimized": "Khởi động thu nhỏ",
        "appearance": "Giao diện",
        "theme": "Theme",
        "system": "Hệ thống",
        "light": "Sáng",
        "dark": "Tối",
        "language": "Ngôn ngữ",
        "panelShortcut": "Phím tắt panel",
        "translation": "Dịch",
        "ignoredApps": "Ứng dụng bỏ qua",
        "analytics": "Phân tích",
        "off": "Tắt",
        "status": "Trạng thái",
        "configuredLocally": "Cấu hình cục bộ",
        "pauseClipboard": "Tạm dừng theo dõi clipboard",
        "clearClipboard": "Xóa lịch sử clipboard",
        "clearClipboardQuestion": "Xóa lịch sử clipboard?",
        "clearClipboardMessage": "Thao tác này xóa vĩnh viễn các mục clipboard cục bộ trên máy Mac này. Các board vẫn được giữ lại.",
        "cloudSync": "Đồng bộ đám mây",
        "privacyBody": "Nội dung clipboard ở lại trên máy Mac này trừ khi bạn bật đồng bộ.",
        "openSettings": "Mở cài đặt"
    ]
}
